name: CI for "Test" keyword

on:
  push:
    branches:
      - main  # main 브랜치에서만 작동

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run CI only if "Test" is in the commit message
        if: contains(github.event.head_commit.message, 'Test')
        run: |
          echo "Running CI for commit containing 'Test'"