name: Build, Push Docker Image and Deploy to AWS EC2

on:
  push:
    paths:
      - '.github/workflows/aws_cicd_final.yaml'

jobs:
  deploy-to-ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # 해당하는 AWS 리전으로 변경

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2의 Public IP 또는 DNS
          username: ubuntu                        # EC2 인스턴스의 사용자 이름 (예: ubuntu, ec2-user)
          key: ${{ secrets.EC2_SSH_KEY }}         # SSH Private Key (PEM 파일 내용)
          port: 22                                 # SSH 포트 (기본값: 22)
          script: |
                whoami
                ls -al