name: 도커 커스텀 빌드 액션

on:
  push:
    paths:
      - '.github/workflows/custom_action_docker_build.yaml'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
      # 커스텀 액션 호출
      - name: Run my custom Docker build/test/push action
        uses: sparta-action-builder@v1 #./.github/actions/custom-docker-build
        with:
          # 위 action.yml에서 정의한 inputs
          image_name: "ryankor/devops-sparta"
          image_tag: "first-cicd-complete-0.0.2"
          context: "04-test-fastapi"
          file: "04-test-fastapi/Dockerfile"

          만약 사용자/패스워드를 받아야 한다면(위 action.yml에서 추가했다면):
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
