name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test-build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ryankor/devops-sparta:fast-api-multi-stage-0.0.1
          load: true
      # 여기서 로컬 컨테이너 실행 후 테스트
      - name: Run Container
        run: |
          # 백그라운드로 컨테이너 실행
          docker run -d --name test-container -p 8000:8000 ryankor/devops-sparta:fast-api-multi-stage-0.0.1
          # 컨테이너가 준비될 때까지 잠시 대기(예: 5초)
          sleep 5

      - name: Test FastAPI Endpoint
        run: |
          RESULT=$(curl -s http://127.0.0.1:8000)
          if echo "$RESULT" | grep '{"Hello": "Sparta"}'; then
            echo "매칭되는 문자열이 발견되었습니다. 종료합니다."
            exit 1
          else
            echo "매칭되는 문자열이 없습니다. 계속 진행합니다."
          fi

      # 테스트 성공시 이미지 푸시(선택사항)
      - name: Push image
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ryankor/devops-sparta:fast-api-multi-stage-0.0.1

      - name: Clean up
        run: |
          docker stop test-container
          docker rm test-container
