name: 첫번째 CI/CD 전체 파이프라인 구축

on:
  push:
    branches:
      - main

jobs:
  metadata-and-code-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3
      
      - name: 메타데이터 추출 및 출력
        run: |
          echo "=== GitHub Actions 러너 메타데이터 ==="
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=100

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: ./04-test-fastapi
          file: ./Dockerfile
          push: false
          tags: ryankor/devops-sparta:first-cicd-complete-0.0.1
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Container
        run: |
          # 백그라운드로 컨테이너 실행
          docker run -d --name test-container -p 8000:8000 ryankor/devops-sparta:first-cicd-complete-0.0.1
          # 컨테이너가 준비될 때까지 잠시 대기(예: 5초)
          sleep 3

      - name: Push image
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: ./04-test-fastapi
          file: ./Dockerfile
          push: true
          tags: ryankor/devops-sparta:first-cicd-complete-0.0.1

      - name: Clean up
        run: |
          docker stop test-container
          docker rm test-container
