name: Homework2

on:
  push:
    paths:
      - '.github/workflows/homework2.yaml'

jobs:
  homework2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run CI only if "build" is in the commit message
        if: contains(github.event.head_commit.message, 'build')
        run: |
          echo "Running CI for commit containing 'build'"