name: Homework4

on:
  push:
    paths:
      - '.github/workflows/homework4.yaml'

jobs:
  homework2:
    runs-on: ubuntu-latest
    steps:
    
      - name: Force Error
        run: |
          echo "이 스텝은 일부로 에러를 발생시킵니다."
          exit 1

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up events even if the job fails or is canceled.