name: Nightly Build and Test

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행
  workflow_dispatch: # 수동 실행을 위한 트리거

jobs:
  metadata-and-code-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3
      
      - name: 메타데이터 추출 및 출력
        run: |
          echo "=== GitHub Actions 러너 메타데이터 ==="
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=100
