name: Second Build Pipeline

# 첫 번째 워크플로우(위에서 name: "First Coverage Pipeline")가
# 완료된 후에 실행되도록 "workflow_run" 트리거 사용
on:
  workflow_run:
    workflows: ["First Coverage Pipeline"]  # 첫 번째 워크플로우의 name과 동일해야 함
    types: 
      - completed  # (completed, requested, in_progress 등 중 선택)

jobs:
  build-and-deploy:
    # 첫 번째 워크플로우가 "success" 결론일 때만 실행
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: 04-test-fastapi
          file: 04-test-fastapi/Dockerfile
          push: false
          tags: ryankor/devops-sparta:first-cicd-complete-0.0.1
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Container
        run: |
          docker run -d --name test-container -p 8000:8000 ryankor/devops-sparta:first-cicd-complete-0.0.1
          sleep 3

      - name: Push image
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: 04-test-fastapi
          file: 04-test-fastapi/Dockerfile
          push: true
          tags: ryankor/devops-sparta:first-cicd-complete-0.0.1

      - name: Clean up
        run: |
          docker stop test-container
          docker rm test-container
